# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0busage.proto\"\x13\n\x11MeterUsageRequest\"\"\n\x12MeterUsageResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2H\n\nMeterUsage\x12:\n\rGetMeterUsage\x12\x12.MeterUsageRequest\x1a\x13.MeterUsageResponse\"\x00\x62\x06proto3'
)




_METERUSAGEREQUEST = _descriptor.Descriptor(
  name='MeterUsageRequest',
  full_name='MeterUsageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=34,
)


_METERUSAGERESPONSE = _descriptor.Descriptor(
  name='MeterUsageResponse',
  full_name='MeterUsageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='MeterUsageResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['MeterUsageRequest'] = _METERUSAGEREQUEST
DESCRIPTOR.message_types_by_name['MeterUsageResponse'] = _METERUSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeterUsageRequest = _reflection.GeneratedProtocolMessageType('MeterUsageRequest', (_message.Message,), {
  'DESCRIPTOR' : _METERUSAGEREQUEST,
  '__module__' : 'usage_pb2'
  # @@protoc_insertion_point(class_scope:MeterUsageRequest)
  })
_sym_db.RegisterMessage(MeterUsageRequest)

MeterUsageResponse = _reflection.GeneratedProtocolMessageType('MeterUsageResponse', (_message.Message,), {
  'DESCRIPTOR' : _METERUSAGERESPONSE,
  '__module__' : 'usage_pb2'
  # @@protoc_insertion_point(class_scope:MeterUsageResponse)
  })
_sym_db.RegisterMessage(MeterUsageResponse)



_METERUSAGE = _descriptor.ServiceDescriptor(
  name='MeterUsage',
  full_name='MeterUsage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=72,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMeterUsage',
    full_name='MeterUsage.GetMeterUsage',
    index=0,
    containing_service=None,
    input_type=_METERUSAGEREQUEST,
    output_type=_METERUSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERUSAGE)

DESCRIPTOR.services_by_name['MeterUsage'] = _METERUSAGE

# @@protoc_insertion_point(module_scope)
